server:
  port: 8083
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: ORDER-SERVICE

logging:
  file:
    name: C:/Users/Phani/Downloads/Other files/Code-base/elk-stack.log

